config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  get 'static_pages/avatar'
  devise_for :users
  root to: 'static_pages#index'
  get '/index/:first_name', to: 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :event

  resources :event do
    resources :attendances
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, presence: true
    validates :duration, presence: true
    validates :title, presence: true, length: {in:5..140}
    validates :description, presence: true, length: {in:20..1000}
    validates :price, presence: true
    validates :location, presence: true
    validate :start_must_be_after_current_time
    validate :duration_must_be_positive
    validate :price_must_be_between_1_1000

    has_many :attendances, dependent: :delete_all
    has_many :users, through: :attendance
    belongs_to :admin, class_name: 'User' 
    
    def start_must_be_after_current_time
        errors.add(:start_date, "Start date cannot be before the current date") unless
        start_date > Date.today
    end

    def duration_must_be_positive
        errors.add(:duration, "Duration cannot be negative") unless
        duration > 0
    end 

    def price_must_be_between_1_1000
        errors.add(:price, "Price must be between 1 and 1000") unless
        price >= 1
        price <= 1000
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    after_create :welcome_send
    has_many :events, through: :attendance
    has_many :events, foreign_key: 'admin_id', class_name: 'Event'

    has_one_attached :avatar

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def show 
    @event = Event.find(params[:event_id])
    @attendance = Attendance.all
  end

  def new
    @attendance = Attendance.create
    @event = Event.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    @user = current_user
    @stripe_amount = @event.price

    begin
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @stripe_amount *100,
        description: "Frais d'incription à un event",
        currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance_path
    end

    @attendance = Attendance.new(stripe_customer_id: customer.id, user: @user, event: @event)
    puts @attendance.inspect

    if @attendance.save
      puts @attendance.inspect
      redirect_to event_path(params[:event_id])
    else 
      puts @attendance.inspect
      flash.now[:alert] = @attendance.errors.full_messages
      render 'new'
    end
    
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
    before_action :authenticate_user!, only: [:create, :new, :edit]

    def index #home
    end

    def show
        @event = Event.find(params[:id])
        @user = current_user
    end

    def new
        @event_new = Event.new# Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    end

    def create
        @event_new = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin_id: current_user.id)

        if @event_new.save
            redirect_to event_path(@event_new.id)
        else
            render :new
        end
    end

    def edit

        @event = Event.find(params[:id])

        if @event.admin_id != current_user.id
            redirect_to :root
        end
        
        # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end
      
    def update

        @event = Event.find(params[:id])

        post_params = params.permit(:start_date, :duration, :title, :description, :price, :location)

        if @event.update(post_params)
            render :show
            flash[:succes] = "Event updated !"
        else 
            render :edit
            flash[:danger] = "Event not updated" 
        end
        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params
        # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to :root
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret] #Pouvoir acceder à une page uniquement en étant connecté

  def index
    @events = Event.all
    @user = current_user
  end

  def secret
    @user = current_user
  end

  def avatar
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/all_pages_helper.rb
module AllPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/current_user_helper.rb
module CurrentUserHelper
    def some_method
      # une méthode et son code
    end
  end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendances/new.html.erb
<div class="d-flex flex-column justify-content-center">
    <h1> Register to : <%= @event.title %></h1>

    <%= form_tag event_attendances_path do %>
    <article>
        <% if flash[:error].present? %>
            <div id="error_explanation">
            <p><%= flash[:error] %></p>
            </div>
        <% end %>
        <label class="amount">
            <span>Amount: <%= @event.price %>€</span>
        </label>
    </article>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Attendance fees to an event"
        data-amount=<%= @stripe_amount %>
        data-locale="fr">
    </script>
    <% end %>
</div>

app/views/attendances/show.html.erb
<h1 class="text-center"> All participants to the event : <%= @event.title %> </h1>

<% @attendance.each do |attendance| %>
    <% if attendance.event_id == @event.id %>
        <li class="text-center"><%= attendance.user.first_name %></li>
    <% end %>
<% end %>

<% if @event.admin_id == current_user.id %>
<p class="text-decoration-none text-center mt-5"><%= link_to "Edit event",  edit_event_path(@event.id), class: "btn btn-danger" %></p>
<% end %>

app/views/event/edit.html.erb
<div style="margin-left:30%; margin-right:30%;">

  <h2> Edit event</h2><hr><br/>

  <%=form_tag url_for(action: 'update'), method: 'patch' do %> 
    <%= text_field_tag 'title', @event.title , class:"form-control" %><br/>
      <%= text_field_tag 'location' , @event.location , class:"form-control" %><br/>
      <%= datetime_field_tag 'start_date' , @event.start_date , class:"form-control" %><br/>
      <%= text_area_tag 'description' , @event.description , class:"form-control" %><br/>
      <%= text_field_tag 'duration' , @event.duration , class:"form-control" %><br/>
      <%= text_field_tag 'price' , @event.price , class:"form-control" %><br/>
      <div class="d-flex flex-row">
        <%= submit_tag "Edit", class: 'btn btn-secondary float-right', style: 'margin-right: 1em' %>
        <%= button_to "Delete event", @event, method: :delete, data:{confirm: "Are you sure you want to delete your event?"}, class:"btn btn-danger float-right" %><br/>
      <div>
  <% end %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


</div>

app/views/event/new.html.erb
<br/><br/><br/>
<div style="margin-left:30%; margin-right:30%;">

  <h2>New event</h2><hr><br/>

  <%=form_tag url_for(action: 'create'), method: 'post' do %> 
    <%= text_field_tag 'title' ,"", class:"form-control", placeholder: "Titre" %><br/>
    <%= text_field_tag 'location' ,"", class:"form-control", placeholder: "Lieu" %><br/>
    <%= datetime_field_tag 'start_date' ,"", class:"form-control", placeholder: Time.zone.now %><br/>
    <%= text_area_tag 'description' ,"", class:"form-control", placeholder: "Description" %><br/>
    <%= text_field_tag 'duration' ,"", class:"form-control", placeholder: "Durée" %><br/>
    <%= text_field_tag 'price' ,"", class:"form-control", placeholder: "Prix" %><br/>
    <%= submit_tag "Créer", class: 'btn btn-secondary float-right' %>
  <% end %>
  <% if @event_new.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @event_new.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

</div>

app/views/event/show.html.erb
<h1 class="text-center pt-5"> This is the page for the event : <%= @event.title %> </h1>
<p class="text-center pt-2"> <%= @event.description %> <p>
<p class="text-center"> Event location : <%= @event.location %></a> <p>
<p class="text-center"> Event admin : <%= @event.admin.first_name %></a> <p>
<p class="text-decoration-none text-center"><%= link_to "Register",  new_event_attendance_path(@event.id), class: "btn btn-danger" %></p>
<% if user_signed_in? && @event.admin_id == @user.id %>
<p class="text-decoration-none text-center"><%= link_to "My event space",  event_attendance_path(@event.id), class: "btn btn-danger" %></p>
<% end %>

app/views/events/new.html.erb
<br/><br/><br/>
<div style="margin-left:30%; margin-right:30%;">

  <h2>New event</h2><hr><br/>

  <%=form_tag url_for(action: 'create'), method: 'post' do %> 
    <%= text_field_tag 'title' ,"", class:"form-control", placeholder: "Titre" %><br/>
    <%= text_field_tag 'location' ,"", class:"form-control", placeholder: "Lieu" %><br/>
    <%= datetime_field_tag 'start_date' ,"", class:"form-control", placeholder: Time.zone.now %><br/>
    <%= text_area_tag 'description' ,"", class:"form-control", placeholder: "Description" %><br/>
    <%= text_field_tag 'duration' ,"", class:"form-control", placeholder: "Durée" %><br/>
    <%= text_field_tag 'price' ,"", class:"form-control", placeholder: "Prix" %><br/>
    <%= submit_tag "Créer", class: 'btn btn-secondary float-right' %>
  <% end %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THPS07Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a><%=link_to "EventBrite", root_path, :class => "navbar-brand"%></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <li><%=link_to "Home", root_path, :class => "nav-link active"%></li>
        </li>
        <li class="nav-item">
          <li><%=link_to "Create event", new_event_path, :class => "nav-link"%></li>
        </li>
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.first_name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%=link_to "Profile", static_pages_secret_path, :class => "dropdown-item" %></li>
              <li><%=link_to "Log Out", destroy_user_session_path, method: :delete, :class => "dropdown-item" %></li>
            </ul>
          <% else %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%=link_to "Register", new_user_registration_path, :class => "dropdown-item" %></li>
              <li><%=link_to "Log In", new_user_session_path, :class => "dropdown-item" %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p class="notice text-center"><%= notice %></p>
<p class="alert text-center"><%= alert %></p>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/avatar.html.erb
<p class="text-center"><%= @user.first_name %>, here you can add a profile pic.</p>
<h3 class="text-center">Your current photo :</h3>
<%if @user.avatar.attached?%>
  <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p class="text-center">=== You did not upload a pic yet ===</p>
<%end%>

app/views/static_pages/index.html.erb
<div id="jumbotron" class="p-5 text-white rounded">
        <% if user_signed_in? %>
        <h1 id="home_title" class="text-center"> Hello <%= current_user.first_name %> ! Welcome to Eventbrite Strasbourg </h1>
        <% else %>
        <h1 id="home_title" class="text-center"> Hello stranger ! Welcome to Eventbrite Strasbourg </h1>
        <% end %>
        <h2 class="text-center"> You can create an event <a <%=link_to "here", new_event_path %></a></h2>
</div>

<h3 id="view_all" class="text-center"> View All Events :</h3>

<div id="section_cards">
    <% @events.each do |event| %>
        <div id="section_cards">
            <div class="card border-0" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= event.title %></h5>
                    <a><%=link_to "Show details", event_path(event.id), :class => "lien_read" %></a>
                    
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/static_pages/secret.html.erb
<h1 class="text-center mb-4"><%= @user.first_name %> ! This is your private page</h1>
<h4 class="text-center"> Your personnal infos :</h4>
<div class="d-flex justify-content-center">
    <div class="card border-0 mb-5" style="width: 18rem;">
        <%= image_tag("", :alt => "", :class => "style_img") %>
        <div class="card-body">
            <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
            <p class="card-text">About me : <%= @user.description %></p>
            <p class="card-text">Email adress : <%= @user.email %></p>
        </div>
    </div>
</div>

<h4 class="text-center mt-5"> Here you can view all of your created events: </h4>

<div id="section_cards">
    <% current_user.events.each do |event| %>
        <div id="section_cards">
            <div class="card border-0" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= event.title %></h5>
                    <a><%=link_to "Show details", event_path(event.id), :class => "lien_read" %></a>
                    <p id="created_on" class="card-text">Created on <%= event.created_at%> by <%= current_user.first_name %></p>  
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/user/show.html.erb
<p><%= @user.first_name %>, here you can add a profile pic.</p>
<h3>Your current pp :</h3>
<%if @user.avatar.attached?%>
  <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p>=== You did not upload a pic yet ===</p>
<%end%>